spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo2
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
#    password: admin
    password: Al3ss10P3sParT3c!
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: mysql
      database-platform: org.hibernate.dialect.MySQLDialect
